version: '3.8'
services:
  redis:
    image: redis:6
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - earthsync-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=password
      - REDIS_EXPORTER_CHECK_SINGLE_KEYS=spectrogram_history:detector1,spectrogram_history:detector2,spectrogram_history:detector3
      - REDIS_EXPORTER_DEBUG=true
    ports:
      - "9121:9121"
    networks:
      - earthsync-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9121/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=earthsync
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - earthsync-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "earthsync"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p
      - DOWNSAMPLE_FACTOR=5
    env_file:
      - ./server/.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - earthsync-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped

  detector1:
    build: ./detector
    environment:
      - DETECTOR_ID=detector1
      - LATITUDE=40.7128  # New York
      - LONGITUDE=-74.0060
    env_file:
      - ./detector/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - earthsync-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  detector2:
    build: ./detector
    environment:
      - DETECTOR_ID=detector2
      - LATITUDE=51.5074  # London
      - LONGITUDE=-0.1278
    env_file:
      - ./detector/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - earthsync-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  detector3:
    build: ./detector
    environment:
      - DETECTOR_ID=detector3
      - LATITUDE=-33.8688  # Sydney
      - LONGITUDE=151.2093
    env_file:
      - ./detector/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - earthsync-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3001:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - earthsync-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - earthsync-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - earthsync-network
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

networks:
  earthsync-network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
