global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'earthsync-server'
    static_configs:
      - targets: ['server:3000']
    scheme: http
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
