global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'earthsync-server'
    static_configs:
      - targets: ['server:3000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
