name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          chmod +x build_and_run.sh
          ./build_and_run.sh

      - name: Wait for test completion
        run: |
          sleep 60  # Wait for containers to start and tests to run
          docker logs earthsync-test > test-output.log 2>&1
          if grep -q "All tests completed successfully" test-output.log; then
            echo "Tests passed!"
          else
            cat test-output.log
            exit 1
          fi

      - name: Clean up
        if: always()
        run: |
          docker stop client earthsync-server earthsync-detector redis postgres earthsync-test 2>/dev/null || true
          docker rm client earthsync-server earthsync-detector redis postgres earthsync-test 2>/dev/null || true
          docker network rm earthsync-network 2>/dev/null || true
